package engine_test

import (
	"context"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.ollin.sh/fmtkit/driver/testutil"
	"go.ollin.sh/fmtkit/formatter/config"
	"go.ollin.sh/fmtkit/formatter/engine"
	"go.ollin.sh/fmtkit/formatter/rules"
	"go.ollin.sh/fmtkit/formatter/rules/spacing"
	"golang.org/x/tools/imports"
)

type gofmtFormatter struct{}

type goimportsFormatter struct{}

type errorRule struct{}

type errorFormatter struct{}

type rewriteFormatter struct{}

func defaultRules() []rules.Rule {
	return []rules.Rule{spacing.New()}
}

func (gofmtFormatter) Name() string {
	return "gofmt"
}

func (gofmtFormatter) Format(src []byte) ([]byte, error) {
	return format.Source(src)
}

func (goimportsFormatter) Name() string {
	return "goimports"
}

func (goimportsFormatter) Format(src []byte) ([]byte, error) {
	return imports.Process("", src, nil)
}

func (errorRule) Name() string {
	return "broken-rule"
}

func (errorRule) Apply(string, []byte) ([]rules.Violation, []byte, error) {
	return nil, nil, errors.New("rule failed")
}

func (errorFormatter) Name() string {
	return "broken-formatter"
}

func (errorFormatter) Format([]byte) ([]byte, error) {
	return nil, errors.New("formatter failed")
}

func (rewriteFormatter) Name() string {
	return "rewrite"
}

func (rewriteFormatter) Format([]byte) ([]byte, error) {
	return []byte("package sample\n\nfunc rewritten() {}\n"), nil
}

func defaultFormatters() []engine.Formatter {
	return []engine.Formatter{gofmtFormatter{}, goimportsFormatter{}}
}

func TestCheckFilesWithNoFilesPasses(t *testing.T) {
	report, err := engine.New(config.Default(), nil, nil).CheckFiles(context.Background(), nil)

	if err != nil {
		t.Fatalf("check files: %v", err)
	}

	if report.Result != "pass" || report.Files != 0 || len(report.Results) != 0 {
		t.Fatalf("unexpected report: %#v", report)
	}
}

func TestCheckFilesReportsExplicitFileChanges(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	testutil.WriteGoFile(t, path, `package sample

func run() {
	defer println("done")
	return
}
`)

	report, err := engine.New(config.Default(), defaultRules(), defaultFormatters()).CheckFiles(context.Background(), []string{path})

	if err != nil {
		t.Fatalf("check files: %v", err)
	}

	if report.Result != "fail" {
		t.Fatalf("expected fail result, got %q", report.Result)
	}

	if report.Files != 1 || report.Changed != 1 {
		t.Fatalf("unexpected report counts: %#v", report)
	}
}

func TestFormatFilesWritesExplicitFiles(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	testutil.WriteGoFile(t, path, `package sample

func run() {
	defer println("done")
	return
}
`)

	report, err := engine.New(config.Default(), defaultRules(), defaultFormatters()).FormatFiles(context.Background(), []string{path})

	if err != nil {
		t.Fatalf("format files: %v", err)
	}

	if report.Result != "fixed" {
		t.Fatalf("expected fixed result, got %q", report.Result)
	}

	content, err := os.ReadFile(path)

	if err != nil {
		t.Fatalf("read file: %v", err)
	}

	if !strings.Contains(string(content), "defer println(\"done\")\n\n\treturn") {
		t.Fatalf("expected file to be rewritten, got:\n%s", content)
	}
}

func TestCollectGoFilesSkipsHiddenVendorAndGenerated(t *testing.T) {
	root := t.TempDir()
	testutil.WriteGoFile(t, filepath.Join(root, "root.go"), "package sample\n")
	testutil.WriteGoFile(t, filepath.Join(root, "pkg", "nested.go"), "package sample\n")
	testutil.WriteGoFile(t, filepath.Join(root, "vendor", "skip.go"), "package sample\n")
	testutil.WriteGoFile(t, filepath.Join(root, ".hidden", "skip.go"), "package sample\n")
	testutil.WriteGoFile(t, filepath.Join(root, "generated.gen.go"), "package sample\n")
	testutil.WriteFile(t, filepath.Join(root, "docker", "Dockerfile.golang"), "FROM golang:1.26.4-bookworm\n")

	files, err := engine.CollectGoFiles([]string{root}, config.Default())

	if err != nil {
		t.Fatalf("collect files: %v", err)
	}

	if len(files) != 2 {
		t.Fatalf("expected 2 files, got %d: %#v", len(files), files)
	}
}

func TestCollectGoFilesAppliesConfiguredExclusionsAndDeduplicates(t *testing.T) {
	root := t.TempDir()
	keep := filepath.Join(root, "keep.go")
	duplicate := filepath.Join(root, "nested", "duplicate.go")
	testutil.WriteGoFile(t, keep, "package sample\n")
	testutil.WriteGoFile(t, duplicate, "package sample\n")
	testutil.WriteGoFile(t, filepath.Join(root, "skip_name.go"), "package sample\n")
	testutil.WriteGoFile(t, filepath.Join(root, "blocked", "skip_path.go"), "package sample\n")
	testutil.WriteFile(t, filepath.Join(root, "not_go.txt"), "package sample\n")
	testutil.WriteGoFile(t, filepath.Join(root, "generated_header.go"), "// Code generated by test. DO NOT EDIT.\npackage sample\n")

	cfg := config.Default()
	cfg.NotName = []string{"skip_*"}
	cfg.NotPath = []string{"blocked/"}

	files, err := engine.CollectGoFiles([]string{root, keep, duplicate}, cfg)

	if err != nil {
		t.Fatalf("collect files: %v", err)
	}

	if len(files) != 2 {
		t.Fatalf("expected 2 files, got %d: %#v", len(files), files)
	}

	for _, want := range []string{keep, duplicate} {
		abs, err := filepath.Abs(want)

		if err != nil {
			t.Fatalf("abs: %v", err)
		}

		found := false

		for _, got := range files {
			if got == abs {
				found = true

				break
			}
		}

		if !found {
			t.Fatalf("expected collected files to include %s: %#v", abs, files)
		}
	}
}

func TestCollectGoFilesReportsMissingPaths(t *testing.T) {
	_, err := engine.CollectGoFiles([]string{filepath.Join(t.TempDir(), "missing")}, config.Default())

	if err == nil {
		t.Fatal("expected missing path error")
	}
}

func TestCollectGoFilesSkipsExplicitGeneratedFiles(t *testing.T) {
	path := filepath.Join(t.TempDir(), "generated.go")
	testutil.WriteGoFile(t, path, "// Code generated by test. DO NOT EDIT.\npackage sample\n")

	files, err := engine.CollectGoFiles([]string{path}, config.Default())

	if err != nil {
		t.Fatalf("collect files: %v", err)
	}

	if len(files) != 0 {
		t.Fatalf("expected generated file to be skipped, got %#v", files)
	}
}

func TestCheckReportsStyleChangesWithoutWriting(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	testutil.WriteGoFile(t, path, `package sample

func run() {
	if true {
		println("ok")
	}
	println("next")
}
`)

	report, err := engine.New(config.Default(), defaultRules(), defaultFormatters()).Check(context.Background(), []string{root})

	if err != nil {
		t.Fatalf("check: %v", err)
	}

	if report.Result != "fail" {
		t.Fatalf("expected fail result, got %q", report.Result)
	}

	if report.Changed != 1 {
		t.Fatalf("expected 1 changed file, got %d", report.Changed)
	}

	content, err := os.ReadFile(path)

	if err != nil {
		t.Fatalf("read file: %v", err)
	}

	if strings.Contains(string(content), "\n\n\tprintln(\"next\")") {
		t.Fatalf("check should not write changes")
	}
}

func TestFormatWritesSpacingChanges(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	testutil.WriteGoFile(t, path, `package sample

func run() {
	defer println("done")
	return
}
`)

	report, err := engine.New(config.Default(), defaultRules(), defaultFormatters()).Format(context.Background(), []string{root})

	if err != nil {
		t.Fatalf("format: %v", err)
	}

	if report.Result != "fixed" {
		t.Fatalf("expected fixed result, got %q", report.Result)
	}

	content, err := os.ReadFile(path)

	if err != nil {
		t.Fatalf("read file: %v", err)
	}

	if !strings.Contains(string(content), "defer println(\"done\")\n\n\treturn") {
		t.Fatalf("expected file to be rewritten, got:\n%s", content)
	}
}

func TestProcessFileReportsReadRuleAndFormatterErrors(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	testutil.WriteGoFile(t, path, "package sample\n")

	tests := []struct {
		name       string
		files      []string
		rules      []rules.Rule
		formatters []engine.Formatter
		wantError  string
	}{
		{
			name:      "read error",
			files:     []string{filepath.Join(root, "missing.go")},
			wantError: "read file:",
		},
		{
			name:      "rule error",
			files:     []string{path},
			rules:     []rules.Rule{errorRule{}},
			wantError: "broken-rule: rule failed",
		},
		{
			name:       "formatter error",
			files:      []string{path},
			formatters: []engine.Formatter{errorFormatter{}},
			wantError:  "broken-formatter: formatter failed",
		},
	}

	for _, tt := range tests {
		tt := tt

		t.Run(tt.name, func(t *testing.T) {
			report, err := engine.New(config.Default(), tt.rules, tt.formatters).CheckFiles(context.Background(), tt.files)

			if err != nil {
				t.Fatalf("check files: %v", err)
			}

			if report.Result != "fail" {
				t.Fatalf("expected fail result, got %q", report.Result)
			}

			if len(report.Results) != 1 {
				t.Fatalf("expected one result, got %#v", report.Results)
			}

			if !strings.Contains(report.Results[0].Error, tt.wantError) {
				t.Fatalf("expected error containing %q, got %q", tt.wantError, report.Results[0].Error)
			}
		})
	}
}

func TestFormatFilesReportsWriteErrors(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root bypasses file permissions, so the read-only file stays writable")
	}

	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	testutil.WriteGoFile(t, path, "package sample\n")

	// The engine replaces files atomically via a sibling temp file, so a
	// read-only directory is what makes the write fail: the temp file can
	// never be created next to the source.
	if err := os.Chmod(root, 0o555); err != nil {
		t.Fatalf("chmod readonly: %v", err)
	}

	t.Cleanup(func() {
		_ = os.Chmod(root, 0o755)
	})

	report, err := engine.New(config.Default(), nil, []engine.Formatter{rewriteFormatter{}}).FormatFiles(context.Background(), []string{path})

	if err != nil {
		t.Fatalf("format files: %v", err)
	}

	if report.Result != "fail" {
		t.Fatalf("expected fail result, got %q", report.Result)
	}

	if len(report.Results) != 1 || !strings.Contains(report.Results[0].Error, "write file:") {
		t.Fatalf("expected write error result, got %#v", report.Results)
	}
}

func TestReportCounts(t *testing.T) {
	report := engine.Report{
		Errors: []engine.ErrorResult{
			{Message: "workspace failed"},
		},
		Results: []engine.FileResult{
			{
				File: "a.go",
				Violations: []rules.Violation{
					{Rule: "spacing", File: "a.go", Message: "first"},
					{Rule: "spacing", File: "a.go", Message: "second"},
				},
			},
			{
				File:  "b.go",
				Error: "read file: denied",
			},
		},
	}

	if got := report.ViolationCount(); got != 2 {
		t.Fatalf("expected 2 violations, got %d", got)
	}

	if got := report.ErrorCount(); got != 2 {
		t.Fatalf("expected 2 errors, got %d", got)
	}
}

func TestFormatIsDeterministicAcrossConcurrencyLevels(t *testing.T) {
	const fileCount = 16

	source := `package sample

func run() {
	defer println("done")
	return
}
`

	makeTree := func(t *testing.T) string {
		t.Helper()

		root := t.TempDir()

		for i := 0; i < fileCount; i++ {
			path := filepath.Join(root, fmt.Sprintf("pkg%02d", i), "sample.go")
			testutil.WriteGoFile(t, path, source)
		}

		return root
	}

	readAll := func(t *testing.T, root string) map[string]string {
		t.Helper()

		got := map[string]string{}

		err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}

			if info.IsDir() || filepath.Ext(path) != ".go" {
				return nil
			}

			data, err := os.ReadFile(path)

			if err != nil {
				return err
			}

			rel, err := filepath.Rel(root, path)

			if err != nil {
				return err
			}

			got[rel] = string(data)

			return nil
		})

		if err != nil {
			t.Fatalf("walk: %v", err)
		}

		return got
	}

	runWith := func(t *testing.T, concurrency int) (engine.Report, map[string]string) {
		t.Helper()

		root := makeTree(t)
		cfg := config.Default()
		cfg.Concurrency = concurrency

		report, err := engine.New(cfg, defaultRules(), defaultFormatters()).Format(context.Background(), []string{root})

		if err != nil {
			t.Fatalf("format (concurrency=%d): %v", concurrency, err)
		}

		return report, readAll(t, root)
	}

	serialReport, serialContent := runWith(t, 1)
	parallelReport, parallelContent := runWith(t, 8)

	if serialReport.Files != parallelReport.Files {
		t.Fatalf("Files mismatch: serial=%d parallel=%d", serialReport.Files, parallelReport.Files)
	}

	if serialReport.Changed != parallelReport.Changed {
		t.Fatalf("Changed mismatch: serial=%d parallel=%d", serialReport.Changed, parallelReport.Changed)
	}

	if serialReport.Result != parallelReport.Result {
		t.Fatalf("Result mismatch: serial=%q parallel=%q", serialReport.Result, parallelReport.Result)
	}

	if len(serialReport.Results) != len(parallelReport.Results) {
		t.Fatalf("Results length mismatch: serial=%d parallel=%d", len(serialReport.Results), len(parallelReport.Results))
	}

	for i := range serialReport.Results {
		s := filepath.Base(filepath.Dir(serialReport.Results[i].File))
		p := filepath.Base(filepath.Dir(parallelReport.Results[i].File))

		if s != p {
			t.Fatalf("Results order diverged at index %d: serial=%s parallel=%s", i, s, p)
		}
	}

	if len(serialContent) != len(parallelContent) {
		t.Fatalf("content map size mismatch: serial=%d parallel=%d", len(serialContent), len(parallelContent))
	}

	for rel, want := range serialContent {
		got, ok := parallelContent[rel]

		if !ok {
			t.Fatalf("missing %s in parallel output", rel)
		}

		if got != want {
			t.Fatalf("content mismatch for %s\n--- serial\n%s\n--- parallel\n%s", rel, want, got)
		}
	}
}

func TestFormatSkipsSingleLineFuncLiteralSpacingViolations(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	testutil.WriteGoFile(t, path, `package sample

type config struct {
	SecureCookie bool
}

func run() config {
	return config{
		SecureCookie: func() bool { value := true; return value }(),
	}
}
`)

	report, err := engine.New(config.Default(), defaultRules(), defaultFormatters()).Format(context.Background(), []string{root})

	if err != nil {
		t.Fatalf("format: %v", err)
	}

	if report.Result != "pass" {
		t.Fatalf("expected pass result, got %q", report.Result)
	}

	if report.Changed != 0 {
		t.Fatalf("expected 0 changed files, got %d", report.Changed)
	}

	if report.ViolationCount() != 0 {
		t.Fatalf("expected 0 violations, got %d", report.ViolationCount())
	}
}
