const PREFIX: &str = "// Code generated ";
const SUFFIX: &str = " DO NOT EDIT.";

/// Whether a source carries a generated-code marker and must be left alone: a
/// `// Code generated ... DO NOT EDIT.` line before the first non-comment line
/// (the Go convention, also honoured for scripts).
///
/// The marker line must match `^// Code generated .* DO NOT EDIT\.$` exactly.
/// Blank lines, `//` and `/* */` comments, a leading byte order mark, and a
/// `#!` first line may precede it.
pub fn is_generated(text: &str) -> bool {
    let text = text.strip_prefix('\u{feff}').unwrap_or(text);
    let mut in_block = false;

    for (number, line) in text.lines().enumerate() {
        if in_block {
            in_block = !line.contains("*/");

            continue;
        }

        if is_marker(line) {
            return true;
        }

        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with("//") || (number == 0 && trimmed.starts_with("#!")) {
            continue;
        }

        let Some(rest) = trimmed.strip_prefix("/*") else {
            return false;
        };

        match rest.find("*/") {
            Some(end) if rest[end + 2..].trim().is_empty() => {}
            Some(_) => return false,
            None => in_block = true,
        }
    }

    false
}

fn is_marker(line: &str) -> bool {
    line.len() >= PREFIX.len() + SUFFIX.len() && line.starts_with(PREFIX) && line.ends_with(SUFFIX)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn go_marker_before_package() {
        assert!(is_generated("// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n"));
        assert!(is_generated("// Copyright 2026\n\n// Code generated by stringer -type=Kind; DO NOT EDIT.\r\npackage x\n"));
        assert!(is_generated("/*\n license\n*/\n// Code generated by x. DO NOT EDIT.\npackage x"));
        assert!(is_generated("\u{feff}// Code generated  DO NOT EDIT."));
    }

    #[test]
    fn marker_after_code_or_malformed_is_ignored() {
        assert!(!is_generated("package x\n\n// Code generated by x. DO NOT EDIT.\n"));
        assert!(!is_generated("// Code generated by x. DO NOT EDIT\npackage x"));
        assert!(!is_generated("// Code generated DO NOT EDIT.\n"));
        assert!(!is_generated("  // Code generated by x. DO NOT EDIT.\n"));
        assert!(!is_generated("/* a */ const x = 1;\n// Code generated by x. DO NOT EDIT.\n"));
        assert!(!is_generated(""));
    }

    #[test]
    fn scripts_may_start_with_a_shebang() {
        assert!(is_generated("#!/usr/bin/env node\n// Code generated by tool. DO NOT EDIT.\nmain();\n"));
        assert!(!is_generated("const a = 1;\n#!/usr/bin/env node\n"));
    }
}
