package planner

import (
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestBuildSelectsEveryChangedGitState(t *testing.T) {
	dir := initRepo(t)
	writeFile(t, filepath.Join(dir, ".gitignore"), "ignored.go\n")
	writeFile(t, filepath.Join(dir, "staged.go"), "package sample\n")
	writeFile(t, filepath.Join(dir, "unstaged.ts"), "const value = 1;\n")
	writeFile(t, filepath.Join(dir, "old.ts"), "const old = true;\n")
	writeFile(t, filepath.Join(dir, "deleted.go"), "package sample\n")
	writeFile(t, filepath.Join(dir, "notes.md"), "before\n")
	run(t, dir, "git", "add", ".")
	run(t, dir, "git", "commit", "-qm", "initial")

	writeFile(t, filepath.Join(dir, "staged.go"), "package sample\n\nconst staged = true\n")
	run(t, dir, "git", "add", "staged.go")
	writeFile(t, filepath.Join(dir, "unstaged.ts"), "const value = 2;\n")
	run(t, dir, "git", "mv", "old.ts", "renamed.ts")
	run(t, dir, "git", "rm", "-q", "deleted.go")
	writeFile(t, filepath.Join(dir, "untracked file.vue"), "<script setup lang=\"ts\"></script>\n")
	writeFile(t, filepath.Join(dir, "ignored.go"), "package ignored\n")
	writeFile(t, filepath.Join(dir, "notes.md"), "after\n")

	plan, err := Build(Options{Cwd: dir})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	want := Plan{
		Go: []string{"staged.go"},
		TS: []string{"renamed.ts", "unstaged.ts", "untracked file.vue"},
	}

	if !reflect.DeepEqual(plan, want) {
		t.Fatalf("plan mismatch\nwant: %#v\n got: %#v", want, plan)
	}
}

func TestBuildLimitsImplicitChangesToNestedCwd(t *testing.T) {
	dir := initRepo(t)
	writeFile(t, filepath.Join(dir, "root.go"), "package sample\n")
	writeFile(t, filepath.Join(dir, "nested", "inside.ts"), "const value = 1;\n")
	run(t, dir, "git", "add", ".")
	run(t, dir, "git", "commit", "-qm", "initial")
	writeFile(t, filepath.Join(dir, "root.go"), "package sample\n\nconst changed = true\n")
	writeFile(t, filepath.Join(dir, "nested", "inside.ts"), "const value = 2;\n")

	plan, err := Build(Options{Cwd: filepath.Join(dir, "nested")})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	want := Plan{TS: []string{"inside.ts"}}

	if !reflect.DeepEqual(plan, want) {
		t.Fatalf("plan mismatch\nwant: %#v\n got: %#v", want, plan)
	}
}

func TestBuildCleanGitRepositoryIsEmpty(t *testing.T) {
	dir := initRepo(t)
	writeFile(t, filepath.Join(dir, "clean.go"), "package sample\n")
	run(t, dir, "git", "add", ".")
	run(t, dir, "git", "commit", "-qm", "initial")

	plan, err := Build(Options{Cwd: dir})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	if len(plan.Go) != 0 || len(plan.TS) != 0 {
		t.Fatalf("clean repository produced work: %#v", plan)
	}
}

func TestBuildHandlesUnbornRepository(t *testing.T) {
	dir := initRepo(t)
	writeFile(t, filepath.Join(dir, ".gitignore"), "ignored.ts\n")
	writeFile(t, filepath.Join(dir, "staged.go"), "package sample\n")
	writeFile(t, filepath.Join(dir, "untracked.d.ts"), "declare const value: string;\n")
	writeFile(t, filepath.Join(dir, "ignored.ts"), "const ignored = true;\n")
	run(t, dir, "git", "add", ".gitignore", "staged.go")

	plan, err := Build(Options{Cwd: dir})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	want := Plan{Go: []string{"staged.go"}, TS: []string{"untracked.d.ts"}}

	if !reflect.DeepEqual(plan, want) {
		t.Fatalf("plan mismatch\nwant: %#v\n got: %#v", want, plan)
	}
}

func TestBuildScansNonGitDirectoryAndClassifiesExactTargets(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "sample.go"), "package sample\n")
	writeFile(t, filepath.Join(dir, "generated.gen.go"), "package sample\n")
	writeFile(t, filepath.Join(dir, "generated.go"), "// Code generated by test. DO NOT EDIT.\npackage sample\n")
	writeFile(t, filepath.Join(dir, "app.ts"), "const value = 1;\n")
	writeFile(t, filepath.Join(dir, "types.d.ts"), "declare const value: string;\n")
	writeFile(t, filepath.Join(dir, "component.vue"), "<template />\n")
	writeFile(t, filepath.Join(dir, "notes.md"), "ignored\n")
	writeFile(t, filepath.Join(dir, "node_modules", "ignored.ts"), "const ignored = true;\n")

	plan, err := Build(Options{Cwd: dir})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	want := Plan{
		Go: []string{"sample.go"},
		TS: []string{"app.ts", "component.vue", "types.d.ts"},
	}

	if !reflect.DeepEqual(plan, want) {
		t.Fatalf("plan mismatch\nwant: %#v\n got: %#v", want, plan)
	}
}

func TestBuildExplicitScopeIsFullEvenWhenGitIsClean(t *testing.T) {
	dir := initRepo(t)
	writeFile(t, filepath.Join(dir, ".gitignore"), "scope/ignored.go\n")
	writeFile(t, filepath.Join(dir, "scope", "tracked.ts"), "const value = 1;\n")
	writeFile(t, filepath.Join(dir, "scope", "ignored.go"), "package ignored\n")
	writeFile(t, filepath.Join(dir, "elsewhere.go"), "package elsewhere\n")
	run(t, dir, "git", "add", ".gitignore", "scope/tracked.ts", "elsewhere.go")
	run(t, dir, "git", "commit", "-qm", "initial")

	plan, err := Build(Options{Cwd: dir, Scopes: []string{"scope"}})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	want := Plan{Go: []string{filepath.Join("scope", "ignored.go")}, TS: []string{filepath.Join("scope", "tracked.ts")}}

	if !reflect.DeepEqual(plan, want) {
		t.Fatalf("plan mismatch\nwant: %#v\n got: %#v", want, plan)
	}
}

func TestBuildExcludesImplicitGitSymlinkCandidates(t *testing.T) {
	dir := initRepo(t)
	external := t.TempDir()
	externalGo := filepath.Join(external, "external.go")
	externalTS := filepath.Join(external, "external.ts")
	writeFile(t, externalGo, "package external\n\nfunc run( ){ }\n")
	writeFile(t, externalTS, "const external = true;\n")

	if err := os.Symlink(externalGo, filepath.Join(dir, "outside.go")); err != nil {
		t.Fatalf("create Go symlink: %v", err)
	}

	if err := os.Symlink(externalTS, filepath.Join(dir, "outside.ts")); err != nil {
		t.Fatalf("create TS symlink: %v", err)
	}

	plan, err := Build(Options{Cwd: dir})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	if len(plan.Go) != 0 || len(plan.TS) != 0 {
		t.Fatalf("symlink candidates escaped implicit planning: %#v", plan)
	}
}

func TestBuildExcludesExplicitSymlinkFilesAndDirectoryEntries(t *testing.T) {
	dir := t.TempDir()
	external := t.TempDir()
	externalGo := filepath.Join(external, "external.go")
	externalTS := filepath.Join(external, "external.ts")
	writeFile(t, externalGo, "package external\n")
	writeFile(t, externalTS, "const external = true;\n")

	if err := os.Symlink(externalGo, filepath.Join(dir, "outside.go")); err != nil {
		t.Fatalf("create Go symlink: %v", err)
	}

	if err := os.Symlink(externalTS, filepath.Join(dir, "outside.ts")); err != nil {
		t.Fatalf("create TS symlink: %v", err)
	}

	for name, scopes := range map[string][]string{
		"direct files":   {"outside.go", "outside.ts"},
		"directory scan": {"."},
	} {
		t.Run(name, func(t *testing.T) {
			plan, err := Build(Options{Cwd: dir, Scopes: scopes})

			if err != nil {
				t.Fatalf("build plan: %v", err)
			}

			if len(plan.Go) != 0 || len(plan.TS) != 0 {
				t.Fatalf("symlink candidates escaped explicit planning: %#v", plan)
			}
		})
	}
}

func TestBuildFailsClosedWhenGitIsUnavailableInApparentCheckout(t *testing.T) {
	dir := t.TempDir()

	if err := os.Mkdir(filepath.Join(dir, ".git"), 0o755); err != nil {
		t.Fatalf("create apparent checkout: %v", err)
	}

	writeFile(t, filepath.Join(dir, "sample.go"), "package sample\n")
	t.Setenv("PATH", t.TempDir())

	_, err := Build(Options{Cwd: dir})

	if err == nil || !strings.Contains(err.Error(), "apparent checkout") {
		t.Fatalf("expected fail-closed Git discovery error, got %v", err)
	}
}

func TestBuildStillScansNonGitDirectoryWhenGitIsUnavailable(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "sample.go"), "package sample\n")
	t.Setenv("PATH", t.TempDir())

	plan, err := Build(Options{Cwd: dir})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	want := Plan{Go: []string{"sample.go"}}

	if !reflect.DeepEqual(plan, want) {
		t.Fatalf("plan mismatch\nwant: %#v\n got: %#v", want, plan)
	}
}

func TestBuildPrefixesDashLeadingRelativeTargets(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "--go.ts"), "const value = 1;\n")

	plan, err := Build(Options{Cwd: dir, Scopes: []string{"--go.ts"}})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	want := Plan{TS: []string{"." + string(filepath.Separator) + "--go.ts"}}

	if !reflect.DeepEqual(plan, want) {
		t.Fatalf("plan mismatch\nwant: %#v\n got: %#v", want, plan)
	}
}

func TestBuildSupportsSymlinkedCwdWhileKeepingTargetsRelative(t *testing.T) {
	dir := initRepo(t)
	writeFile(t, filepath.Join(dir, "nested", "inside.ts"), "const value = 1;\n")
	run(t, dir, "git", "add", ".")
	run(t, dir, "git", "commit", "-qm", "initial")
	writeFile(t, filepath.Join(dir, "nested", "inside.ts"), "const value = 2;\n")
	alias := filepath.Join(t.TempDir(), "checkout")

	if err := os.Symlink(filepath.Join(dir, "nested"), alias); err != nil {
		t.Fatalf("create cwd symlink: %v", err)
	}

	plan, err := Build(Options{Cwd: alias})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	want := Plan{TS: []string{"inside.ts"}}

	if !reflect.DeepEqual(plan, want) {
		t.Fatalf("plan mismatch\nwant: %#v\n got: %#v", want, plan)
	}
}

func TestBuildNonGitScanSkipsDefaultContainedRuntimeCache(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CACHE_HOME", filepath.Join(home, ".cache"))
	t.Setenv("GO_FMT_RUNTIME_DIR", "")
	cacheRoot, err := os.UserCacheDir()

	if err != nil {
		t.Fatalf("resolve user cache: %v", err)
	}

	writeFile(t, filepath.Join(home, "sample.ts"), "const value = 1;\n")
	writeFile(t, filepath.Join(cacheRoot, "go-fmt", "contained", "runtime", "bundled.go"), "package runtime\n")
	writeFile(t, filepath.Join(cacheRoot, "go-fmt", "contained", "runtime", "bundled.ts"), "const bundled = true;\n")

	plan, err := Build(Options{Cwd: home})

	if err != nil {
		t.Fatalf("build plan: %v", err)
	}

	want := Plan{TS: []string{"sample.ts"}}

	if !reflect.DeepEqual(plan, want) {
		t.Fatalf("default runtime cache escaped exclusion\nwant: %#v\n got: %#v", want, plan)
	}
}

func initRepo(t *testing.T) string {
	t.Helper()

	dir := t.TempDir()
	run(t, dir, "git", "init", "-q")
	run(t, dir, "git", "config", "user.email", "tests@example.com")
	run(t, dir, "git", "config", "user.name", "Test Runner")

	return dir
}

func writeFile(t *testing.T, path, contents string) {
	t.Helper()

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("create parent: %v", err)
	}

	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func run(t *testing.T, dir, name string, args ...string) {
	t.Helper()

	cmd := exec.Command(name, args...)
	cmd.Dir = dir

	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("%s %v: %v\n%s", name, args, err, output)
	}
}
