[package]
name = "fmtkit-discover"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
fmtkit-config.workspace = true
fmtkit-core.workspace = true
gix.workspace = true
ignore.workspace = true
postcard.workspace = true
rayon.workspace = true
serde.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
kqueue.workspace = true
rustix = { workspace = true, features = ["process"] }

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { workspace = true, features = ["fs"] }

[dev-dependencies]
tempfile.workspace = true
